import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["CODERRUPEE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["CODERRUPEE_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("CODERRUPEE_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  CODERRUPEE_AUTO_HEAP_SNAPSHOT: truthy("CODERRUPEE_AUTO_HEAP_SNAPSHOT"),
  CODERRUPEE_GIT_BASH_PATH: process.env["CODERRUPEE_GIT_BASH_PATH"],
  CODERRUPEE_CONFIG: process.env["CODERRUPEE_CONFIG"],
  CODERRUPEE_CONFIG_CONTENT: process.env["CODERRUPEE_CONFIG_CONTENT"],
  CODERRUPEE_DISABLE_AUTOUPDATE: truthy("CODERRUPEE_DISABLE_AUTOUPDATE"),
  CODERRUPEE_ALWAYS_NOTIFY_UPDATE: truthy("CODERRUPEE_ALWAYS_NOTIFY_UPDATE"),
  CODERRUPEE_DISABLE_PRUNE: truthy("CODERRUPEE_DISABLE_PRUNE"),
  CODERRUPEE_DISABLE_TERMINAL_TITLE: truthy("CODERRUPEE_DISABLE_TERMINAL_TITLE"),
  CODERRUPEE_SHOW_TTFD: truthy("CODERRUPEE_SHOW_TTFD"),
  CODERRUPEE_DISABLE_AUTOCOMPACT: truthy("CODERRUPEE_DISABLE_AUTOCOMPACT"),
  CODERRUPEE_DISABLE_MODELS_FETCH: truthy("CODERRUPEE_DISABLE_MODELS_FETCH"),
  CODERRUPEE_DISABLE_MOUSE: truthy("CODERRUPEE_DISABLE_MOUSE"),
  CODERRUPEE_FAKE_VCS: process.env["CODERRUPEE_FAKE_VCS"],
  CODERRUPEE_SERVER_PASSWORD: process.env["CODERRUPEE_SERVER_PASSWORD"],
  CODERRUPEE_SERVER_USERNAME: process.env["CODERRUPEE_SERVER_USERNAME"],
  CODERRUPEE_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("CODERRUPEE_DISABLE_FFF"),

  // Experimental
  CODERRUPEE_EXPERIMENTAL_FILEWATCHER: Config.boolean("CODERRUPEE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CODERRUPEE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("CODERRUPEE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  CODERRUPEE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("CODERRUPEE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  CODERRUPEE_MODELS_URL: process.env["CODERRUPEE_MODELS_URL"],
  CODERRUPEE_MODELS_PATH: process.env["CODERRUPEE_MODELS_PATH"],
  CODERRUPEE_DB: process.env["CODERRUPEE_DB"],

  CODERRUPEE_WORKSPACE_ID: process.env["CODERRUPEE_WORKSPACE_ID"],
  CODERRUPEE_EXPERIMENTAL_WORKSPACES: enabledByExperimental("CODERRUPEE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get CODERRUPEE_DISABLE_PROJECT_CONFIG() {
    return truthy("CODERRUPEE_DISABLE_PROJECT_CONFIG")
  },
  get CODERRUPEE_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("CODERRUPEE_EXPERIMENTAL_REFERENCES")
  },
  get CODERRUPEE_TUI_CONFIG() {
    return process.env["CODERRUPEE_TUI_CONFIG"]
  },
  get CODERRUPEE_CONFIG_DIR() {
    return process.env["CODERRUPEE_CONFIG_DIR"]
  },
  get CODERRUPEE_PURE() {
    return truthy("CODERRUPEE_PURE")
  },
  get CODERRUPEE_PERMISSION() {
    return process.env["CODERRUPEE_PERMISSION"]
  },
  get CODERRUPEE_PLUGIN_META_FILE() {
    return process.env["CODERRUPEE_PLUGIN_META_FILE"]
  },
  get CODERRUPEE_CLIENT() {
    return process.env["CODERRUPEE_CLIENT"] ?? "cli"
  },
}
